import GlobalContextProvider from "@/context/GlobalContext";
import "../styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GlobalContextProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </GlobalContextProvider>
  );
}
